//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerJuanMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int comentario_id { get; set; }
        public Nullable<int> cita_id { get; set; }
        public string tipo { get; set; }
        public string comentario_texto { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
